name: camera_awesome
description: Easiest Flutter camera Plugin with builtin UI. Supporting capturing images, streaming images, video recording, switch sensors, autofocus, flash, filters... on Android and iOS.
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/camera_awesome
repository: https://github.com/SunnatilloShavkatov/camera_awesome

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  flutter:
    sdk: flutter
  image: ^4.2.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  matrix2d: ^1.0.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^19.0.0

flutter:
  assets:
    - assets/icons/1_1.png
    - assets/icons/16_9.png
    - assets/icons/4_3.png

  plugin:
    platforms:
      android:
        package: com.apparence.camera_awesome.cameraX
        pluginClass: CameraAwesomeX
      ios:
        pluginClass: CamerawesomePlugin
